apiVersion: batch/v1
kind: Job
metadata:
  name: call-argo-events
  annotations:
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: curl
        image: curlimages/curl:latest
        command: ["curl"]
        args:
          - -X
          - POST
          - -H
          - "X-Webhook-Token: my-secret-token"
          - http://argocd-sync.argo-events.svc.cluster.local:12000/argocd-sync
      restartPolicy: Never
  backoffLimit: 2
